# SPDX-FileCopyrightText: 2025 Anthony Accioly <anthony@accioly.dev>
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - cloudflare-tunnel

networks:
  cloudflare-tunnel:
    name: cloudflare-tunnel
