# SPDX-FileCopyrightText: 2025 Anthony Accioly <anthony@accioly.dev>
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    restart: unless-stopped
    ports:
      - "${THELOUNGE_PORT:-9000}:9000"
      - "${THELOUNGE_IDENTD_PORT:-113}:113"
    volumes:
      - ./data:/var/opt/thelounge
    networks:
      - cloudflare-tunnel

networks:
  cloudflare-tunnel:
    external: true
