# SPDX-FileCopyrightText: 2025 Anthony Accioly <anthony@accioly.dev>
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  clipcascade:
    image: sathvikrao/clipcascade:latest
    container_name: clipcascade
    restart: unless-stopped
    ports:
      - "${CLIPCASCADE_PORT:-8080}:8080"
    volumes:
      - ./data:/database
    environment:
      - CC_MAX_MESSAGE_SIZE_IN_MiB=${CC_MAX_MESSAGE_SIZE_IN_MiB:-1}
      - CC_P2P_ENABLED=${CC_P2P_ENABLED:-false}
      - CC_ALLOWED_ORIGINS=${CC_ALLOWED_ORIGINS}
      - CC_SIGNUP_ENABLED=${CC_SIGNUP_ENABLED:-true}
    networks:
      - cloudflare-tunnel

networks:
  cloudflare-tunnel:
    external: true
